project:
  type: website
  output-dir: docs

website:
  title: "Michael Zargari"
  favicon: images/logo.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: volunteer_leadership.qmd
        text: School Leadership & Volunteering
      - href: https://eddatascienceees.github.io/tutorial-mzargari/
        text: SQL Tutorial
   #   - href: posts.qmd
    #    text: Blog

format:
  html:
    theme: lux
     # dark: lux
   #   light: flatly
    css: styles.css
    toc: true

