project:
  type: website
  output-dir: docs

website:
  title: "Michael Zargari"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: fav_repos_and_sites.qmd
        text: Repositories and Websites

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

