project:
  type: website
  output-dir: docs

website:
  title: "Michael Zargari"
  favicon: images/logo.png
  navbar:
    right:
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: volunteer_leadership.qmd
        text: Volunteering and School Leadership
      - href: https://eddatascienceees.github.io/tutorial-mzargari/
        text: SQL Tutorial

format:
  html:
    theme: 
      dark: lux
      light: flatly
    css: styles.css
    toc: true

editor: visual

